### ISSUE TITLE
Where is the Save Location?

### ISSUE THREAD

**Issue by AnotherBlob** [zhaowenlan1779/threeSD#10]
I don't know where threeSD (the Windows exe) exports files to. I know it's in C: (which isn't ideal, because I don't have any space there) but it's not written anywhere where exactly it saves to.
Might be obvious to some but... not to me.

**Comment by zhaowenlan1779** [comment]
It imports data to the citra user folder, which is %appdata%/Citra on windows. By default, Citra should automatically pick up your imported files.

**Comment by AnotherBlob** [comment]
Thank you!
