### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by TheLastMelody** [zhaowenlan1779/threeSD#11]
Apparently random crashes when importing. Tried to import from 3DS via microSD management tool, by copying the whole MicroSD onto my hard drive and choosing the root of the micro SD and by copying the microSD card content onto a USB stick formatted as FAT32. All resulted in crash. I have followed the quickstart guide and have run the script before doing any of the other things. It does not appear to crash on a specific file. Running as admin changes nothing. Forgot to mention that it takes longer for it to crash if I use MicroSD Management to slowly process the files over WiFi.

EDIT:
I got it working, but only for smaller files over WiFi with MicroSD Management. The larger files (the games) still crash it. Cut-off for crash seems to be around 150MB. I managed to import the game Harvest Moon:Skytree Village, which is only 90MB and it works.

**Comment by zhaowenlan1779** [comment]
Please test the latest commit, thanks!

**Comment by TheLastMelody** [comment]
After having spent the last hour on trying to understand how to build anything from source on Github (I assume I'd need to do that to test latest commit) and after bothering a friend-ish fella for another thirty minutes, he advised me to just ask you to build and send it to me. So, uhh, can you please build it with latest commit and send it to me?

**Comment by zhaowenlan1779** [comment]
Get a build from appveyor: https://ci.appveyor.com/project/zhaowenlan1779/threesd/builds/34868220/artifacts

**Comment by TheLastMelody** [comment]
Sorry for taking so long.
It appears to be working perfectly now, I ran it through the same tests as those where it crashed in my post up above. Thanks for fixing.
