### ISSUE TITLE
Imports to wrong folder for Flatpak install on Fedora 33

### ISSUE THREAD

**Issue by suchipi** [zhaowenlan1779/threeSD#15]
Hello,

I installed Citra via Flatpak on my Fedora 33 machine. Its Citra folder is:
```
~/.var/app/org.citra_emu.citra/data/citra-emu
```
However, threeSD imports content into:
```
~/.local/share/citra-emu/
```

This was surprising to me because the [QuickStart Guide](https://github.com/zhaowenlan1779/threeSD/wiki/Quickstart-Guide) said to open the binary directly when using Flatpak, and the app UI itself said "Import destination: User-wide Citra install."

I worked around this issue by creating a symlink.

Thanks for making this tool! It worked fantastically. Looking forward to playing my 3DS games at high resolution.

**Comment by zhaowenlan1779** [comment]
Should be fixed in v0.6.0
