### ISSUE TITLE
Bulk options for building CIAs?

### ISSUE THREAD

**Issue by DioVento** [zhaowenlan1779/threeSD#16]
As far as I know, this is the only PC-based tool for managing a 3DS formatted SD card. It has the really useful feature of being able to right click a game and build a backup CIA file, but only one at a time and the name for the file must be manually entered for each game. Would it be possible to allow the selection and batch creation of CIAs for multiple games in one task, or perhaps some command line options for it?

**Comment by zhaowenlan1779** [comment]
Added in v0.6.0
