### ISSUE TITLE
Change import destination based on Citra's config

### ISSUE THREAD

**Issue by tstephenson888** [zhaowenlan1779/threeSD#17]
I'm having trouble using threeSD due to low disk space. I use a small solid-state drive to boot up my operating system some important applications I use.

Because Citra installs its virtual SD card and NAND to the main drive's AppData folder by default, whenever I try to run threeSD, it stops due to low disk space on the main drive. However, I changed the Citra config so that the virtual SD and NAND are put onto another drive. For whatever reason, this is not reflected within threeSD, and the program tries to import my files to the default AppData directory anyways...

Is there any way I can change where exactly threeSD imports its files to?

**Comment by zhaowenlan1779** [comment]
The feature to change storage directories in Citra was only recently added. I'll try to implement a fix in a bit.

**Comment by zhaowenlan1779** [comment]
Should be fixed in v0.6.0
