### ISSUE TITLE
Unjustified "Version dismatch" 

### ISSUE THREAD

**Issue by Ness404** [zhaowenlan1779/threeSD#18]
I did use the files from the same release of ThreeSD, yet the software still detects a "Version Dismatch" what could I do to fix this ? Also, I noticed that, when it is done dumping, GodMode9 (I'm using version 1.7.0) shows an error message saying "unknown cmd", does that perhaps have something to do with my initial problem ? Thanks in advance for any help.

**Comment by zhaowenlan1779** [comment]
Yes, you'll need to update GodMode9, since the command used to write threeSD version info is not supported on an older version of GM9.
