### ISSUE TITLE
Script can't run in GM9

### ISSUE THREAD

**Issue by shawnshyguy** [zhaowenlan1779/threeSD#2]
Hey, I was following along to the guide [here](https://github.com/zhaowenlan1779/threeSD), but when i try to run the script, GM9 just says this:
`0:/gm9/scripts/threeSDumper.gm9
line 9: too many arguments
if not find $[OUT] NULL
(<A> to continue)`

I'm not sure if the fault is mine, or if there's a problem with the script, but it might be worth looking into.

**Comment by zhaowenlan1779** [comment]
Hi! What's the version of your GM9? I believe you may need to update it.

**Comment by zhaowenlan1779** [comment]
Closing as obsolete
