### ISSUE TITLE
boot9.bin is not in VRAM if fastboot3DS is used

### ISSUE THREAD

**Issue by min1up** [zhaowenlan1779/threeSD#3]
[fastboot3DS](https://github.com/derrekr/fastboot3DS) is a bootloader for the 3DS recommended by GodMode9. In a vanilla installation of fastboot3DS, boot9.bin is not in VRAM. The script will fail every time when trying to copy boot9.bin.

In a normal installation of fastboot3DS (at least on my 3DS), boot9.bin should already be in `/gm9/out`.

#### Workarounds
My hotfix was to comment the line that performs the boot9 copy operation and manually copy over boot9.bin. I personally recommend:
- Modifying the GM9 script to check if boot9.bin is in `/gm9/out` _second_ (fastboot3DS is optional) and copy when found.
- Changing the wiki to notify the user to either change fastboot3DS settings (untested and lacks documentation) or to chainload GM9 through Luma3DS instead of fastboot3DS.

**Comment by zhaowenlan1779** [comment]
Fixed by adding a second check to copy from `0:/3DS/boot9.bin`. This is what you get by `Miscellaneous... > Dump bootroms & OTP` in the fastboot3ds menu (hold HOME while booting). An error message is shown when the file is not found in both places.
