### ISSUE TITLE
Crash when opening Jap filesystem folder linked to rednand

### ISSUE THREAD

**Issue by Liger0** [zhaowenlan1779/threeSD#4]
The app works when I select the folder of my EU nand, but it insta-crashes when selecting the japanese one, altough it's reported as "good", because it's the one linked to my regionchanged rednand.
Would it be possible to dump the files in the rednand in the future too? 
Thanks.

**Comment by zhaowenlan1779** [comment]
Huh, I'm not exactly sure why you would have different ID0s between SysNAND and EmuNAND. Can you please provide more information like what you did to create the EmuNAND?

**Comment by Liger0** [comment]
I used Tinyformat to unlink them.

**Comment by zhaowenlan1779** [comment]
Should be fixed in v0.6.0
