### ISSUE TITLE
Build failure on linux in import_dialog.cpp

### ISSUE THREAD

**Issue by Kirtai** [zhaowenlan1779/threeSD#5]
On Kubuntu 19.10 with kde backports (Qt 5.12) I get the following error while building:

`[ 91%] Building CXX object src/frontend/CMakeFiles/threeSD.dir/import_dialog.cpp.o
/home/faith/projects/3DS/threeSD/src/frontend/import_dialog.cpp: In member function ‘void ImportDialog::InsertSecondLevelItem(std::size_t, const Core::ContentSpecifier&, std::size_t, QString, QPixmap)’:

/home/faith/projects/3DS/threeSD/src/frontend/import_dialog.cpp:194:35: error: conversion from ‘std::size_t’ {aka ‘long unsigned int’} to ‘const QVariant’ is ambiguous

  194 |     checkBox->setProperty("id", id);
      |                                   ^
compilation terminated due to -Wfatal-errors.

make[2]: *** [src/frontend/CMakeFiles/threeSD.dir/build.make:76: src/frontend/CMakeFiles/threeSD.dir/import_dialog.cpp.o] Error 1

make[1]: *** [CMakeFiles/Makefile2:455: src/frontend/CMakeFiles/threeSD.dir/all] Error 2

make: *** [Makefile:84: all] Error 2
`

**Comment by zhaowenlan1779** [comment]
Fixed and added a Linux CI, thanks for reporting!
