### ISSUE TITLE
Any chance of a Linux version?

### ISSUE THREAD

**Issue by WandeingLagomorph793** [zhaowenlan1779/threeSD#8]
Currently it doesn't work under WINE and the only option for Linux users is loading it under a Windows VM.

**Comment by zhaowenlan1779** [comment]
Sure. There's already a linux CI, I'll look into publishing releases soon.

**Comment by zhaowenlan1779** [comment]
Added in [v0.5.1](https://github.com/zhaowenlan1779/threeSD/releases/tag/v0.5.1)
